### ISSUE TITLE
想问下什么时候会公开代码

### ISSUE THREAD

**Issue by Simon-max2020** [alphadl/SafeLLM_with_IntentionAnalysis#1]
对你们的工作很感兴趣

**Comment by alphadl** [comment]
Thanks for your attention to our work! We will finish the cleaning up and upload the code within 1 month. Stay tuned :)

**Comment by Simon-max2020** [comment]
> Thanks for your attention to our work! We will finish the cleaning up and upload the code within 1 month. Stay tuned :)

In your experiment part, you use gpt-3.5-turbo-0613 for evaluation through the specific prompt. I'm curious about the parameters setting for gpt, such as temperature, presence_penalty, top_k...

**Comment by alphadl** [comment]
> > Thanks for your attention to our work! We will finish the cleaning up and upload the code within 1 month. Stay tuned :)
> 
> In your experiment part, you use gpt-3.5-turbo-0613 for evaluation through the specific prompt. I'm curious about the parameters setting for gpt, such as temperature, presence_penalty, top_k...

Please refer to the response at https://github.com/alphadl/SafeLLM_with_IntentionAnalysis/issues/2

**Comment by ruiyeNLP** [comment]
also looking forward to your code

**Comment by sudarshan-kamath** [comment]
Looking forward to your code

**Comment by alphadl** [comment]
@ruiyeNLP @sudarshan-kamath thanks for your patience, we will upload the cleaned code next week

**Comment by vergilus** [comment]
建议 paper 里给具体的 prompt case，看完都没概念这个 intention analysis prompt 具体是什么内容。其实这个 idea 很容易想到，但具体工程落地才是重要的。

**Comment by alphadl** [comment]
> 建议 paper 里给具体的 prompt case，看完都没概念这个 intention analysis prompt 具体是什么内容。其实这个 idea 很容易想到，但具体工程落地才是重要的。

thanks for your suggestion! we have uploaded the detailed prompts in GitHub and will update them on the paper ASAP.
