### ISSUE TITLE
The parameter setting of the experiment part

### ISSUE THREAD

**Issue by Simon-max2020** [alphadl/SafeLLM_with_IntentionAnalysis#2]
In your experiment part, you use gpt-3.5-turbo-0613 for evaluation through the specific prompt. I'm curious about the parameters setting for gpt, such as temperature, presence_penalty, top_k...

**Comment by alphadl** [comment]
We set the temperature to 0 for deterministic and consistent evaluation results, and the max_tokens is set to 10. We left other parameters at their default settings; for instance, the presence_penalty is 0. More details about the default can be found at https://platform.openai.com/docs/api-reference/chat/create
